name = "v20251104"
main = "_worker.js"
compatibility_date = "2025-11-04"
account_id = "47120fe4af4d0bd09be128a755ce84fc"
workers_dev = true
keep_vars = true

# ADMIN must be configured as a Cloudflare Secret.
[[kv_namespaces]]
binding = "KV"
id = "aa43e96253264020afbeee328b28a5b8"
